server:
  port: 1111
spring:
  application:
    name: eureka-server1

eureka:
  # begin  配置关闭自我保护，并配置Eureka Server清理无效节点的时间间隔
#  server:
#    enable-self-preservation: false         # 设为false，关闭自我保护
#    eviction-interval-timer-in-ms: 30000   # 清理间隔（单位毫秒，默认是60*1000）
  # end
  instance: 
    hostname: patern-eureka-server
#    perferIpAddress: true
  client:
    register-with-eureka: false  # 当前服务不需要到Eureka Server上注册
    fetch-registry: false  # 不需要从eureka服务器获取注册信息
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:1112/eureka/,http://${eureka.instance.hostname}:1113/eureka/   # Eureka客户端设置Eureka Server的地址

logging:
#  config: classpath:logback/logback-${spring.profiles.active}.xml
  path: logs/
  file: eureka-server-1.log
