server:
  port: 7001

spring:
  application:
    name: config-server
#  profiles:
#    active: native    #开启本地配置 默认为git
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: E:\\git\\patern-spring-cloud\\config-server\\config-repo
# git管理配置
  cloud:
    config:
      username: patern
      password:  
      label: master
      server:
        git:
          uri: https://github.com/patern/spring-cloud
          searchPaths: config-server/config-repo
         
